server:
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/departmentDetails
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  spring:
    sql:
      init:
        mode: never
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

hibernate:
  temp:
    use_jdbc_metadata_defaults: false